-- V1__init.sql  — Leave Management System schema
-- Portable: H2 (MODE=PostgreSQL) and PostgreSQL 10+
-- No CREATE TYPE / JSONB / BIGSERIAL / TIMESTAMPTZ

-- ── Team ────────────────────────────────────────────────────────────────────
CREATE TABLE team (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                         VARCHAR(120) NOT NULL UNIQUE,
    max_concurrent_leave_percent NUMERIC(5,2) NOT NULL DEFAULT 30,
    productive_hours_per_day     NUMERIC(4,1) NOT NULL DEFAULT 6,
    created_at                   TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- ── Employee ────────────────────────────────────────────────────────────────
CREATE TABLE employee (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120) NOT NULL,
    email         VARCHAR(200) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'EMPLOYEE'
                  CONSTRAINT chk_employee_role CHECK (role IN ('EMPLOYEE','MANAGER','HR','ADMIN')),
    team_id       BIGINT       REFERENCES team(id),
    manager_id    BIGINT       REFERENCES employee(id),
    join_date     DATE         NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    capacity_fte  NUMERIC(4,2) NOT NULL DEFAULT 1.0,
    job_role      VARCHAR(80),
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_employee_team    ON employee(team_id);
CREATE INDEX idx_employee_manager ON employee(manager_id);
CREATE INDEX idx_employee_email   ON employee(email);

-- ── Leave Type ───────────────────────────────────────────────────────────────
CREATE TABLE leave_type (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                    VARCHAR(20)  NOT NULL UNIQUE
                            CONSTRAINT chk_leave_code CHECK (code IN ('ANNUAL','SICK','CASUAL','UNPAID')),
    name                    VARCHAR(80)  NOT NULL,
    annual_entitlement_days NUMERIC(5,1) NOT NULL,
    requires_balance        BOOLEAN      NOT NULL DEFAULT TRUE
);

-- ── Leave Balance ─────────────────────────────────────────────────────────────
CREATE TABLE leave_balance (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT       NOT NULL REFERENCES employee(id),
    leave_type_id   BIGINT       NOT NULL REFERENCES leave_type(id),
    "year"          INT          NOT NULL,
    entitled        NUMERIC(6,1) NOT NULL DEFAULT 0,
    used            NUMERIC(6,1) NOT NULL DEFAULT 0,
    pending         NUMERIC(6,1) NOT NULL DEFAULT 0,
    carried_forward NUMERIC(6,1) NOT NULL DEFAULT 0,
    CONSTRAINT uq_balance UNIQUE (employee_id, leave_type_id, "year")
);

CREATE INDEX idx_balance_emp_year ON leave_balance(employee_id, "year");

-- ── Holiday ──────────────────────────────────────────────────────────────────
CREATE TABLE holiday (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date    DATE         NOT NULL,
    name    VARCHAR(120) NOT NULL,
    team_id BIGINT       REFERENCES team(id)    -- NULL = company-wide
);

CREATE INDEX idx_holiday_date ON holiday(date);

-- ── Peak Period ───────────────────────────────────────────────────────────────
CREATE TABLE peak_period (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id    BIGINT       NOT NULL REFERENCES team(id),
    from_date  DATE         NOT NULL,
    to_date    DATE         NOT NULL,
    multiplier NUMERIC(4,2) NOT NULL DEFAULT 1.0,
    name       VARCHAR(80)  NOT NULL,
    CONSTRAINT chk_peak_dates CHECK (to_date >= from_date)
);

-- ── Leave Request ─────────────────────────────────────────────────────────────
CREATE TABLE leave_request (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id            BIGINT       NOT NULL REFERENCES employee(id),
    leave_type_id          BIGINT       NOT NULL REFERENCES leave_type(id),
    start_date             DATE         NOT NULL,
    end_date               DATE         NOT NULL,
    working_days           NUMERIC(5,1) NOT NULL,
    reason                 TEXT,
    status                 VARCHAR(20)  NOT NULL DEFAULT 'PENDING_MANAGER'
                           CONSTRAINT chk_leave_status CHECK (status IN (
                               'PENDING_MANAGER','PENDING_HR','ESCALATED',
                               'APPROVED','REJECTED','CANCELLED')),
    current_stage_deadline TIMESTAMP,
    escalation_level       INT          NOT NULL DEFAULT 0,
    conflict_flag          BOOLEAN      NOT NULL DEFAULT FALSE,
    feasibility_percent    NUMERIC(5,2),
    conflict_summary       TEXT,
    created_at             TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMP    NOT NULL DEFAULT NOW(),
    version                BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT chk_leave_dates CHECK (end_date >= start_date)
);

CREATE INDEX idx_leave_employee ON leave_request(employee_id);
CREATE INDEX idx_leave_status   ON leave_request(status);
CREATE INDEX idx_leave_dates    ON leave_request(start_date, end_date);
CREATE INDEX idx_leave_deadline ON leave_request(current_stage_deadline);

-- ── Approval History ──────────────────────────────────────────────────────────
CREATE TABLE approval_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_request_id BIGINT      NOT NULL REFERENCES leave_request(id),
    actor_id         BIGINT      REFERENCES employee(id),   -- NULL = SYSTEM
    from_status      VARCHAR(20),
    to_status        VARCHAR(20) NOT NULL,
    action           VARCHAR(30) NOT NULL
                     CONSTRAINT chk_leave_action CHECK (action IN (
                         'SUBMIT','MANAGER_APPROVE','MANAGER_REJECT',
                         'HR_APPROVE','HR_REJECT','ESCALATE','CANCEL')),
    comment          TEXT,
    created_at       TIMESTAMP   NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_history_request ON approval_history(leave_request_id);
CREATE INDEX idx_history_actor   ON approval_history(actor_id);

-- ── Notification ──────────────────────────────────────────────────────────────
CREATE TABLE notification (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT   NOT NULL REFERENCES employee(id),
    message     TEXT     NOT NULL,
    read        BOOLEAN  NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notification_emp ON notification(employee_id, read);

-- ── Workload Upload Batch ─────────────────────────────────────────────────────
CREATE TABLE workload_upload_batch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id     BIGINT       NOT NULL REFERENCES team(id),
    file_name   VARCHAR(255) NOT NULL,
    uploaded_by BIGINT       REFERENCES employee(id),
    row_count   INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- ── Workload Task ─────────────────────────────────────────────────────────────
CREATE TABLE workload_task (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id      BIGINT       NOT NULL REFERENCES workload_upload_batch(id) ON DELETE CASCADE,
    team_id       BIGINT       NOT NULL REFERENCES team(id),
    name          VARCHAR(200) NOT NULL,
    effort_hours  NUMERIC(8,2) NOT NULL,
    start_date    DATE         NOT NULL,
    due_date      DATE         NOT NULL,
    priority      VARCHAR(10)  NOT NULL DEFAULT 'MEDIUM'
                  CONSTRAINT chk_task_priority CHECK (priority IN ('HIGH','MEDIUM','LOW')),
    required_role VARCHAR(80),
    CONSTRAINT chk_task_dates CHECK (due_date >= start_date)
);

CREATE INDEX idx_task_team_dates ON workload_task(team_id, start_date, due_date);
CREATE INDEX idx_task_batch      ON workload_task(batch_id);

-- ── Generated Report ──────────────────────────────────────────────────────────
CREATE TABLE generated_report (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         VARCHAR(30)  NOT NULL DEFAULT 'MONTHLY_APPROVED',
    period_from  DATE         NOT NULL,
    period_to    DATE         NOT NULL,
    file_path    VARCHAR(500) NOT NULL,
    row_count    INT          NOT NULL DEFAULT 0,
    generated_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    generated_by BIGINT       REFERENCES employee(id),
    CONSTRAINT uq_report UNIQUE (type, period_from, period_to)
);
